
export enum UserRole {
  GUEST = 'GUEST',
  STUDENT = 'STUDENT',
  ADMIN = 'ADMIN'
}

export interface User {
  id: string;
  name: string;
  role: UserRole;
  avatarUrl: string;
  username?: string; // New: Login ID
  password?: string; // New: Login Password
  hasPaid?: boolean; // New: Payment Status
}

export interface Instructor {
  id: string;
  name: string;
  bio: string;
  imageUrl: string;
}

export interface ClassSession {
  id: string;
  title: string;
  dayOfWeek: number; // 1 = Monday, 7 = Sunday
  startTimeStr: string; // "09:00"
  durationMinutes: number;
  instructorId: string;
  capacity: number;
  enrolledUserIds: string[];
  location: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  isSubstitute: boolean;
  originalInstructorId?: string;
  notificationMessage?: string; // Message generated by AI
}

// For state context
export interface AppState {
  currentUser: User;
  classes: ClassSession[];
  instructors: Instructor[];
  students: User[]; // Expose students for admin to manage
}

export interface AppContextType extends AppState {
  // Auth
  login: (username: string, password: string) => boolean;
  logout: () => void;
  isLoginModalOpen: boolean;
  setLoginModalOpen: (isOpen: boolean) => void;

  bookClass: (classId: string, userId?: string) => void;
  cancelClass: (classId: string, userId?: string) => void;
  
  // Class Management
  addClass: (classData: Omit<ClassSession, 'id' | 'enrolledUserIds' | 'isSubstitute'>) => void;
  updateClass: (id: string, updates: Partial<ClassSession>) => void;
  deleteClass: (id: string) => void;

  updateClassInstructor: (classId: string, newInstructorId: string, notification?: string) => void;
  addInstructor: (name: string, bio: string) => string; // Returns new ID
  deleteInstructor: (id: string) => void;
  // Student Management
  addStudent: (student: Partial<User>) => string; // Updated to accept object
  updateStudent: (id: string, updates: Partial<User>) => void;
  deleteStudent: (id: string) => void;
  
  // Helper
  getNextClassDate: (dayOfWeek: number, timeStr: string) => Date;
}
